### ISSUE TITLE
Gear pickup causes follower to equip amaranthine prism

### ISSUE THREAD

**Issue by ghost** [Kizby/Clever-Girl#22]
![amaranthineprism](https://user-images.githubusercontent.com/3055384/104865794-0e4d2980-5991-11eb-80aa-138bb07bebc5.png)

Not sure if you'd actually _want_ to fix this-- on the one hand I now can't finish the quest (until companion dies at least), but on the other hand having your mushroom gather village mayor esper companion's mind slowly taken over by Ptoh is extremely Caves of Qud

(awesome mod btw!)

**Comment by Kizby** [comment]
Ha, oh noooo! I think I'll just make companions avoid picking up objects with the Cursed part, has nice symmetry with Nethack's approach. That should still allow /discerning/ leaders to give cursed items to companions if desired.

(glad you like it! <3)

**Comment by Kizby** [comment]
Fixed at 79ff6667c9488578bcf0fecfbadb237cd61481e7, will be in the next update

**Comment by ghost** [comment]
Nice work! 👍
